[package]
name = "sih-workflow"
version.workspace = true
edition.workspace = true

[dependencies]
chrono.workspace = true
sih-domain = { path = "../domain" }
uuid.workspace = true
sqlx = { version = "0.8", features = ["runtime-tokio-native-tls", "postgres", "uuid", "chrono"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
